### ISSUE TITLE
Does not work in latest version

### ISSUE THREAD

**Issue by tom-dierckx** [wso2-ballerina/package-soap#5]
Will there be a new package for version 0.964.0?

Regards,
Tom Dierckx

**Comment by ldclakmal** [comment]
@tom-dierckx The current code base is up-to date with Ballerina latest version **Ballerina 0.973.0**

**Comment by anupama-pathirage** [comment]
@tom-dierckx Closing this issue as per the above comment. Please raise if you have further queries on this.
