### ISSUE TITLE
Where is the jar file?

### ISSUE THREAD

**Issue by pmhofman** [wso2-ballerina/package-soap#6]
**Description:**

According the README.md, there should be a jar file in the zip file to be downloaded from https://github.com/ballerinalang/connector-soap/releases
I unzipped, but did not find the jar file

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
n/a

**Steps to reproduce:**
download https://github.com/wso2-ballerina/package-soap/archive/v0.95.1.zip
unzip
don't find the jar ;)

**Related Issues:**

**Comment by pmhofman** [comment]
maybe https://maven.wso2.org/nexus/content/repositories/releases/org/ballerinalang/ballerina-soap/0.95.1/ was meant?

**Comment by pmhofman** [comment]
accidentally closed it

**Comment by ldclakmal** [comment]
@pmhofman The current code base is up-to date with Ballerina latest version [Ballerina 0.973.0](https://ballerina.io/downloads/). With that update there is no need of external _jar_ files. You can find a working example at [README.md](https://github.com/wso2-ballerina/package-soap/blob/master/README.md)

**Comment by pmhofman** [comment]
Ok, cool! Thanks! I will check it out.

**Comment by anupama-pathirage** [comment]
@pmhofman Closing this issue as per the above comment. Thanks for providng us the feedback and please raise if you have further queries on this.
